package com.masabi.cloudfit.outfit

import com.masabi.cloudfit.ai.GeneratedImage
import com.masabi.cloudfit.ai.ImageModel
import com.masabi.cloudfit.ai.Part
import com.masabi.cloudfit.shared.Clothe
import com.masabi.cloudfit.shared.ClothingCategory
import com.masabi.cloudfit.storage.LocalImageStore
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import java.net.URI
import java.nio.file.Files
import java.nio.file.Path

private class FakeImageModel(private val bytes: ByteArray) : ImageModel {
    override suspend fun generateImage(model: String, parts: List<Part>) =
        GeneratedImage(bytes, "image/png")
}

private class BoomImageModel : ImageModel {
    override suspend fun generateImage(model: String, parts: List<Part>): GeneratedImage = error("model down")
}

class GeminiImageRendererTest : StringSpec({

    val garment = Clothe(id = "t1", category = ClothingCategory.TOP, imageUrl = "x", colour = "white")

    "saves the generated bytes and returns a readable url" {
        val dir: Path = Files.createTempDirectory("cloudfit-test")
        val store = LocalImageStore(dir)
        val renderer = GeminiImageRenderer(FakeImageModel("PNGDATA".toByteArray()), store, "fake-image-model")

        val result = renderer.render(listOf(garment), avatarImageUrl = null)

        result.imageUrl.shouldNotBeNull()
        Files.readAllBytes(Path.of(URI.create(result.imageUrl))) shouldBe "PNGDATA".toByteArray()
    }

    "reports failure (not a crash) when the model throws" {
        val dir = Files.createTempDirectory("cloudfit-test")
        val renderer = GeminiImageRenderer(BoomImageModel(), LocalImageStore(dir), "fake-image-model")

        val result = renderer.render(listOf(garment), avatarImageUrl = null)

        result.imageUrl shouldBe null
        result.failed shouldBe true
    }
})
