package app.cloudfit.styling.infrastructure.adapter.output.ai

import app.cloudfit.shared.application.ai.GeneratedImage
import app.cloudfit.shared.application.ai.ImageModel
import app.cloudfit.shared.application.ai.Part
import app.cloudfit.shared.domain.ClothingCategory
import app.cloudfit.shared.testing.InMemoryImageStore
import app.cloudfit.styling.domain.WardrobeItem
import io.kotest.assertions.throwables.shouldThrowAny
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import java.util.UUID

private class RecordingImageModel(private val bytes: ByteArray) : ImageModel {
    val calls = mutableListOf<List<Part>>()

    override suspend fun generateImage(model: String, parts: List<Part>): GeneratedImage {
        calls += parts
        return GeneratedImage(bytes, "image/png")
    }
}

private class BoomImageModel : ImageModel {
    override suspend fun generateImage(model: String, parts: List<Part>): GeneratedImage = error("model down")
}

class LlmOutfitImageRendererTest : StringSpec({

    "sends the avatar and garment images from the store and returns the generated bytes" {
        val store = InMemoryImageStore()
        val avatar = store.put("AVATAR".toByteArray(), "image/jpeg")
        val shirt = store.put("SHIRT".toByteArray(), "image/png")
        val model = RecordingImageModel("PNGDATA".toByteArray())
        val clothe = WardrobeItem(UUID.randomUUID(), ClothingCategory.TOP, shirt.url, colour = "white")

        val image = LlmOutfitImageRenderer(model, store, "fake-image-model").render(listOf(clothe), avatar.url)

        image.bytes.toList() shouldBe "PNGDATA".toByteArray().toList()
        val parts = model.calls.single()
        parts.size shouldBe 3
        parts[0].inlineData!!.mimeType shouldBe "image/jpeg"
        parts[1].inlineData!!.mimeType shouldBe "image/png"
        parts[2].text!! shouldContain "the exact person in the first image"
        parts[2].text!! shouldContain "top (reference image 2): white"
    }

    "propagates model failures so the look can be refunded" {
        val store = InMemoryImageStore()
        val shirt = store.put("SHIRT".toByteArray(), "image/png")
        val clothe = WardrobeItem(UUID.randomUUID(), ClothingCategory.TOP, shirt.url)

        shouldThrowAny { LlmOutfitImageRenderer(BoomImageModel(), store, "m").render(listOf(clothe), null) }
    }
})
